{
  "type": "record",
  "namespace": "com.pstysz.airquality.model",
  "name": "SensorWithStationData",
  "fields": [
    {
      "name": "sensorId",
      "type": "string"
    },
    {
      "name": "stationId",
      "type": "string"
    },
    {
      "name": "stationName",
      "type": "string"
    },
    {
      "name": "locality",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "countryId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "sensorName",
      "type": "string"
    },
    {
      "name": "units",
      "type": "string"
    },
    {
      "name": "sensorDisplayName",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "value",
      "type": "double"
    },
    {
      "name": "datetimeLast",
      "type": "string"
    },
    {
      "name": "fetchDateTime",
      "type": "string"
    }
  ]
}
