spring:
  application:
    name: stream-processor

custom:
  kafka:
    bootstrap-servers: kafka:9092
    schema-registry: http://schema-registry:8081
    topics:
      sensor-measurements: air-quality.sensor-measurements
      measuring-stations: air-quality.measuring-stations
      sensor-with-station-data: air-quality.sensor-with-station-data
      sensor-to-station: air-quality.sensor-to-station
      agg-measurement-5m: air-quality.agg-measurement-5m
      agg-measurement-1h: air-quality.agg-measurement-1h
      measurement-trend: air-quality.measurement-trend