spring:
  application:
    name: stream-processor

custom:
  kafka:
    bootstrap-servers: kafka:9092
    measurements-topic: air-quality.measurements
    stations-topic: air-quality.stations
    schema-registry: http://schema-registry:8081